services:
  app:
    image: ghcr.io/all-right-consultoria/landing-page-app:latest
    pull_policy: always
    command: gunicorn allright.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/web/assets
      - media_volume:/home/app/web/media
      - db_volume:/home/app/web/db
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    image: ghcr.io/all-right-consultoria/landing-page-nginx:latest
    pull_policy: always
    volumes:
      - static_volume:/home/app/web/assets
      - media_volume:/home/app/web/media
      - "$(readlink -f /etc/letsencrypt/live/allright-consultoria.com.br/fullchain.pem)":/etc/nginx/ssl/fullchain.pem
      - "$(readlink -f /etc/letsencrypt/live/allright-consultoria.com.br/privkey.pem)":/etc/nginx/ssl/privkey.pem
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
  db_volume:
